import { type Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";

import { AuthProvider } from "@global/providers/AuthProvider";
import { StoreProvider } from "@global/providers/StoreProvider";
import { COOKIE_TOKEN_NAME } from "@shared/constants/cookiesNames";
import { getCookie } from "@shared/libs/serverCookie";

import "@shared/assets/styles/index.scss";

const geistSans = Geist({
   variable: "--font-geist-sans",
   subsets: ["latin"]
});

const geistMono = Geist_Mono({
   variable: "--font-geist-mono",
   subsets: ["latin"]
});

export const metadata: Metadata = {
   title: "Create Next App",
   description: "Generated by create next app"
};

export default async function RootLayout({
   children
}: Readonly<{
   children: React.ReactNode;
}>) {
   const token = await getCookie(COOKIE_TOKEN_NAME);

   return (
      <html lang="en">
         <body className={`${geistSans.variable} ${geistMono.variable}`}>
            <StoreProvider jwtToken={token}>
               <AuthProvider>{children}</AuthProvider>
            </StoreProvider>
         </body>
      </html>
   );
}
